"use server";

/**
 * AI INSIGHTS ACTIONS
 * This file handles fetching automated business insights.
 * These insights are typically generated by a background process and stored in 'ai_insights'.
 */

export interface AIInsightRow {
  id: string;
  insight_type: string; // e.g., 'inventory_risk', 'sales_opportunity'
  title: string;
  description: string | null;
  severity: string; // e.g., 'low', 'medium', 'high'
  data: any; // Extra contextual data for the insight
  created_at: string;
}

import supabase from "@/lib/db";

/**
 * Fetches the latest AI insights from the database.
 * Returns an empty array gracefully if the table is missing or empty.
 */
export async function getAIInsights(): Promise<AIInsightRow[]> {
  try {
    const { data, error } = await supabase
      .from("ai_insights")
      .select("*")
      .order("created_at", { ascending: false });

    if (error) {
      // It's possible the 'ai_insights' table hasn't been created yet.
      // We log a warning instead of failing the page.
      console.warn("AI insights table not available:", error.message);
      return [];
    }

    // Process rows to ensure the 'data' field is a proper JSON object
    return (data || []).map((row: any) => ({
      ...row,
      data: typeof row.data === "string" ? JSON.parse(row.data) : row.data,
    }));
  } catch (error) {
    console.error("Error fetching AI insights:", error);
    return [];
  }
}
